services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:${MONGO_PASSWORD}@mongodb:27017/vlon-prod?authSource=admin

  mongodb:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: [--auth]

  caddy:
    image: caddy:2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - api

  mongo-proxy:
    image: nginx:alpine
    ports:
      - '27018:27018'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  mongodb-data:
  caddy_data:
  caddy_config:
