services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/coinvester-dev
      - NODE_ENV=development

  mongodb:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  mongodb-data: